### ISSUE TITLE
Veil-Evasion | [Version]: 2.17.0 [Unable to execute]

### ISSUE THREAD

**Issue by mabdu** [Veil-Framework/Veil-Evasion#115]
Can any one please help me. I have download Veil-Evasion 100 times and tried to install it on Kali 1.1.0a both on VM and my PC but I am unable to run it. Always following error 

=========================================================================
 Veil-Evasion | [Version]: 2.17.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 283, in <module>
    controller = controller.Controller(oneRun=False)
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 129, in __init__
    self.LoadPayloads()
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 141, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil/Veil-Evasion/modules/common/controller.py", line 141, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil/Veil-Evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/root/Veil/Veil-Evasion/tools/backdoor/pebin.py", line 42, in <module>
    import pefile
ImportError: No module named pefile

Please help

**Comment by ChrisTruncer** [comment]
This is a duplicate, we've answered this a couple times in our closed issues. Please search there for the fix.
