### ISSUE TITLE
Hey Guy's the install doesn't like Kali too much 

### ISSUE THREAD

**Issue by n0x00** [Veil-Framework/Veil-Evasion#130]
Is there something silly I'm missing ? - many thanks :)

#1 SMP Debian 3.14.5-1kali1 (2014-06-07)

root@WhyFight:~/Veil-Evasion# ./Veil-Evasion.py 

=========================================================================
 Veil-Evasion | [Version]: 2.19.0
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 283, in <module>
    controller = controller.Controller(oneRun=False)
  File "/root/Veil-Evasion/modules/common/controller.py", line 129, in __init__
    self.LoadPayloads()
  File "/root/Veil-Evasion/modules/common/controller.py", line 141, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil-Evasion/modules/common/controller.py", line 141, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/root/Veil-Evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/root/Veil-Evasion/tools/backdoor/pebin.py", line 41, in <module>
    import pefile
ImportError: No module named pefile
root@WhyFight:~/Veil-Evasion#

**Comment by n0x00** [comment]
eurgh, pefile hah sorry guys !
