### ISSUE TITLE
Issue with capstone

### ISSUE THREAD

**Issue by vailixi** [Veil-Framework/Veil-Evasion#175]
For some reason capstone didn't install correctly when I install veil-evasion. So I tried installing it a few different ways. I'm getting this error: veil cannot find capstone: I ran this to find it:
cat /etc/ld.so.conf.d/capstone.conf
# Capstone Shared Libs
/usr/lib64

is it installed to the wrong location? What should I do here?

veil-evasion

=========================================================================
 Veil-Evasion | [Version]: 2.20
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================

Traceback (most recent call last):
  File "./Veil-Evasion.py", line 283, in <module>
    controller = controller.Controller(oneRun=False)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 129, in __init__
    self.LoadPayloads()
  File "/usr/share/veil-evasion/modules/common/controller.py", line 141, in LoadPayloads
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/usr/share/veil-evasion/modules/common/controller.py", line 141, in <genexpr>
    d = dict( (path[path.find("payloads")+9:-3], imp.load_source( "/".join(path.split("/")[3:])[:-3],path )  ) for path in glob.glob(join(settings.VEIL_EVASION_PATH+"/modules/payloads/" + "*/" * x,'[!_]*.py')) )
  File "/usr/share/veil-evasion//modules/payloads/native/backdoor_factory.py", line 14, in <module>
    from tools.backdoor import pebin
  File "/usr/share/veil-evasion/tools/backdoor/pebin.py", line 45, in <module>
    from intel.intelCore import intelCore
  File "/usr/share/veil-evasion/tools/backdoor/intel/intelCore.py", line 38, in <module>
    from capstone import *
ImportError: No module named capstone

**Comment by ChrisTruncer** [comment]
Please run the setup script
