### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by jonw18** [Veil-Framework/Veil-Evasion#305]
## OS Used - all info (architecture, linux flavor, etc) Kali Linux

cp: cannot create regular file '/usr/share/pyinstaller/support/loader/Windows-32bit/runw.exe': No such file or directory
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 339, in <module>
    controller.MainMenu(args=args)
  File "/root/tools/Veil/Veil-Evasion/modules/common/controller.py", line 871, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/root/tools/Veil/Veil-Evasion/modules/common/controller.py", line 802, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/root/tools/Veil/Veil-Evasion/modules/common/controller.py", line 608, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/root/tools/Veil/Veil-Evasion/modules/common/supportfiles.py", line 127, in supportingFiles
    and not os.path.isfile(settings.WINEPREFIX + 'drive_c/Python27/python.exe')\
AttributeError: 'module' object has no attribute 'WINEPREFIX'

**Comment by ChrisTruncer** [comment]
This is a duplicate issue.  Please search to find other issues which have the answer already in them before creating a new issue.

Please just run the update.py script

**Comment by jonw18** [comment]
Sorry, should have searched harder. My bad.
Appreciate your help
Thank you.

**Comment by ChrisTruncer** [comment]
No problem, hope it works well for you now

**Comment by jonw18** [comment]
Works great.
Apparently I need to work just as good :)

Thanks for the quick response.
