### ISSUE TITLE
could not build payload

### ISSUE THREAD

**Issue by bkr32** [Veil-Framework/Veil-Evasion#378]
## Veil-Evasion version
2.28.1

## OS Used - all info (architecture, linux flavor, etc)
Kali 2 Rolling

## Pastebin link to error you are encountering (include console actions you took prior to error)

```
Payload: ruby/meterpreter/rev_tcp loaded


 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 COMPILE_TO_EXE  	Y       	Compile to an executable
 LHOST           	        	IP of the Metasploit handler
 LPORT           	4444    	Port of the Metasploit handler

 Available Commands:

	set         	Set a specific option value
	info        	Show information about the payload
	options     	Show payload's options
	generate    	Generate payload
	back        	Go to the main menu
	exit        	exit Veil-Evasion

 [ruby/meterpreter/rev_tcp>>]: set lhost 
 [i] LHOST => 
 [ruby/meterpreter/rev_tcp>>]: generate

=========================================================================
 Veil-Evasion | [Version]: 2.28.1
=========================================================================
 [Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================


 [>] Please enter the base name for output files (default is 'payload'): test-veil
Traceback (most recent call last):
  File "Veil-Evasion.py", line 339, in <module>
    controller.MainMenu(args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 976, in MainMenu
    self.outputFileName = self.PayloadMenu(self.payload, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 806, in PayloadMenu
    return self.OutputMenu(payload, payloadCode, args=args)
  File "/root/Veil-Evasion/modules/common/controller.py", line 612, in OutputMenu
    supportfiles.supportingFiles(self.payload, OutputFileName, {})
  File "/root/Veil-Evasion/modules/common/supportfiles.py", line 197, in supportingFiles
    os.system('WINEPREFIX=' + settings.WINEPREFIX + ' wine ' + settings.WINEPREFIX + '/drive_c/Ruby187/bin/ruby.exe ' + settings.WINEPREFIX + '/drive_c/Ruby187/bin/ocra --windows '+ payloadFile + ' --output ' + settings.PAYLOAD_COMPILED_PATH + exeName + ' ' + settings.WINEPREFIX + '/drive_c/Ruby187/lib/ruby/gems/1.8/gems/win32-api-1.4.8-x86-mingw32/lib/win32/*')
AttributeError: 'module' object has no attribute 'WINEPREFIX'
```

## Expected behavior
should create a pyaload

## Any additional info you want to tell me
nice framework

**Comment by ChrisTruncer** [comment]
Please run the update.py script.  This issue is present and has been documented in other Github issues, check them out too

**Comment by bkr32** [comment]
the update.py in /config?
