### ISSUE TITLE
Readline module missing

### ISSUE THREAD

**Issue by miguelkennedy** [Veil-Framework/Veil-Evasion#455]
## Veil-Evasion version
Latest (13th May, 2017)

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017.1 x64

## Pastebin link to error you are encountering (include console actions you took prior to error)
After running setup.sh -c successfully, when I try to run ./Veil.py I get the following error:
Traceback (most recent call last):
  File "./Veil.py", line 7, in <module>
    from lib.common import orchestra
  File "/root/github/PayloadsGenerators/Veil/lib/common/orchestra.py", line 10, in <module>
    import readline
ImportError: No module named 'readline'

Thanks!

**Comment by ChrisTruncer** [comment]
As stated at the very top of this project, Veil-Evasion is no longer supported. Please use Veil 3.0

**Comment by jelassi93** [comment]
Am using Veil 3.0 and i have the same problem:
`root@dhcppc3:~/Téléchargements/Veil-master# ./Veil.py
Traceback (most recent call last):
  File "./Veil.py", line 7, in <module>
    from lib.common import orchestra
  File "/root/Téléchargements/Veil-master/lib/common/orchestra.py", line 10, in <module>
    import readline
ImportError: No module named 'readline'`
help me and thanks
